export const personalInfo = {
  name: "Antonio Santana",
  email: "devantonio.fer@gmail.com",
  website: "https://antoniosantana.site",
  linkedin: "https://www.linkedin.com/in/dev-antonio-fernandes/",
  github: "https://github.com/antonionetu",
  whatsapp: "https://wa.me/+37125562433",
  instagram: "https://instagram.com/antonio.santanadev",
};

export const experiences = [
  {
    key: "atos",
    company: "Atos Capital",
    role: "Developer",
    type: "Porto Digital Partnership",
    period: "Jan 2026 - Present",
    location: "Aracaju, Brazil",
    description:
      "Working in partnership with Porto Digital on financial technology solutions. Atos Capital provides financial solutions for large ERPs including reconciliation, payments, expenses management, and credit products for enterprises across Brazil.",
    techs: [
      "C#",
      ".NET",
      "PostgreSQL",
      "AWS",
      "REST APIs",
      "Microservices",
      "Docker",
    ],
  },
  {
    key: "vox",
    company: "Vox",
    role: "Mid-Level Full Stack Developer",
    type: "Full-time",
    period: "Sep 2025 - Present",
    location: "Aracaju, Brazil",
    description:
      "Full stack development at an EdTech company. Building and maintaining platform features using C#/.NET and AWS services. Working with AI-powered features, payment gateway integrations, database management, CI/CD pipelines, and quality assurance processes. Mentoring junior developers and conducting weekly technical sessions.",
    techs: [
      "C#",
      ".NET",
      "PostgreSQL",
      "AWS",
      "Docker",
      "Redis",
      "CI/CD",
      "GitHub Actions",
      "Stripe",
      "S3",
      "Lambda",
      "xUnit",
    ],
  },
  {
    key: "quantum",
    company: "Quantum Educacional",
    role: "Full Stack Developer",
    type: "Full-time",
    period: "Jun 2023 - Sep 2025",
    location: "S\u00e3o Paulo, Brazil (Remote)",
    description:
      "Developed and maintained platforms such as EZ, DocStudios and Instituto Terra with 30,000+ users, using Django with Python and Vue.js with JavaScript/TypeScript. Integrated third-party services like Sebrae, ensuring effective communication between RESTful APIs and internal systems. Implemented unit and E2E automated tests with Selenium, simulating real user interactions to ensure quality and robustness. Managed async tasks and process scheduling using Celery with Redis, improving application scalability and performance. Acted as tech lead on projects, organizing sprints, mentoring team members and ensuring on-time deliveries with quality. Performed significant refactoring of legacy code applying Design Patterns and SOLID principles, increasing maintainability, performance and readability. Modeled and administered production and staging databases in MySQL and PostgreSQL, including data correction and migration scripts. Used AWS services (EC2, S3, RDS) for hosting, storage and application management, ensuring high availability and scalability.",
    techs: [
      "Django",
      "Python",
      "Vue.js",
      "JavaScript",
      "TypeScript",
      "MySQL",
      "PostgreSQL",
      "AWS",
      "Selenium",
      "Celery",
      "Redis",
      "REST APIs",
    ],
  },
  {
    key: "apoio",
    company: "Apoio Fiel",
    role: "Backend Developer",
    type: "Porto Digital Partnership",
    period: "Jan 2024 - Jun 2024",
    location: "Aracaju, Brazil",
    description:
      "Apoio Fiel is a solution that helps other NGOs manage their donations. Developed the API using Express, applying best practices to ensure a scalable and maintainable architecture. Modeled and managed the database with Prisma ORM, optimizing queries and data integrity. Documented API endpoints with Swagger, facilitating team communication and integration with external systems. Led the technical team, coordinating tasks, reviewing code and promoting development best practices.",
    techs: [
      "Node.js",
      "Express",
      "Prisma",
      "Swagger",
      "TypeScript",
      "PostgreSQL",
      "Jest",
    ],
  },
  {
    key: "sinqia",
    company: "Sinqia (via rethinqit)",
    role: "Frontend Developer",
    type: "Outsourced",
    period: "Jan 2024 - Apr 2024",
    location: "Remote",
    description:
      "Sinqia is a company in the financial segment integrated with banks. Developed pages and components using Angular, applying best practices to ensure performance and scalability. Managed tasks and demands using agile methodologies, ensuring deadline compliance while maintaining team communication.",
    techs: ["Angular", "SASS", "TypeScript", "RxJS", "Jasmine", "REST APIs"],
  },
  {
    key: "tiradentes",
    company: "Grupo Tiradentes",
    role: "Frontend Developer",
    type: "Porto Digital Partnership",
    period: "Jul 2023 - Dec 2023",
    location: "Aracaju, Brazil",
    description:
      "Grupo Tiradentes is a company in the higher education segment. In partnership with Porto Digital, redesigned Magister, the system used by UNIT, focusing on improved usability, performance and responsiveness. Led the team, organizing tasks, promoting best practices and ensuring on-time deliveries. Developed interfaces using React, JavaScript and TypeScript. Managed code versioning using Git, ensuring rigorous version control, code reviews and continuous integration.",
    techs: [
      "React",
      "TypeScript",
      "JavaScript",
      "Styled Components",
      "REST APIs",
      "Figma",
    ],
  },
  {
    key: "workana",
    company: "Workana (Freelance)",
    role: "Freelance Developer",
    type: "Freelance",
    period: "Jan 2020 - Dec 2021",
    location: "Remote",
    description:
      "Workana is a company that connects freelancers to businesses or individuals. Developed responsive web applications using React, Next.js and Tailwind CSS, delivering modern and performant interfaces. Collaborated directly with clients to understand their needs, proposing scalable and customized technical solutions for each business. Integrated RESTful and GraphQL APIs for efficient front-end and back-end communication. Implemented unit tests to ensure application quality and stability.",
    techs: [
      "React",
      "Next.js",
      "Tailwind CSS",
      "GraphQL",
      "Node.js",
      "Vercel",
      "Figma",
    ],
  },
];

export const education = [
  {
    key: "rtu",
    institution: "Riga Technical University (RTU)",
    degree: "Bachelor\u2019s - Computer Systems",
    period: "Jan 2025 - Jul 2025",
    location: "Riga, Latvia",
    url: "https://www.rtu.lv/en",
  },
  {
    key: "unit",
    institution: "Universidade Tiradentes (UNIT)",
    degree: "Bachelor\u2019s - Computer Science",
    period: "Feb 2023 - Jun 2027",
    location: "Aracaju, Brazil",
    url: "https://www.unit.br",
    extra: ["mentor", "researcher"],
  },
];

export const skills = {
  backend: [
    "C#",
    ".NET",
    "Python",
    "Django",
    "FastAPI",
    "Node.js",
    "Express",
    "Go",
    "REST APIs",
    "GraphQL",
    "Microservices",
  ],
  frontend: [
    "React",
    "Next.js",
    "Vue.js",
    "Angular",
    "TypeScript",
    "JavaScript",
    "Tailwind CSS",
    "Styled Components",
  ],
  database: [
    "PostgreSQL",
    "MySQL",
    "SQL Server",
    "MongoDB",
    "Redis",
    "Prisma",
    "Entity Framework",
  ],
  devops: [
    "Docker",
    "AWS (EC2, S3, RDS, Lambda)",
    "CI/CD",
    "GitHub Actions",
    "Linux",
    "Nginx",
    "Vercel",
  ],
  tools: [
    "Scrum",
    "Figma",
    "Postman",
    "Insomnia",
    "ClickUp",
    "Swagger",
  ],
  ai: [
    "Claude AI",
    "ChatGPT",
    "GitHub Copilot",
    "Cypress",
    "Selenium",
    "xUnit",
    "Jest",
  ],
};

export const languages = [
  { key: "portuguese" as const, levelKey: "native" as const },
  { key: "english" as const, levelKey: "fluent" as const },
  { key: "spanish" as const, levelKey: "intermediate" as const },
  { key: "russian" as const, levelKey: "basic" as const },
  { key: "latvian" as const, levelKey: "basic" as const },
];

export const navSections = [
  { id: "home", key: "home" as const },
  { id: "about", key: "about" as const },
  { id: "experience", key: "experience" as const },
  { id: "skills", key: "skills" as const },
  { id: "education", key: "education" as const },
  { id: "contact", key: "contact" as const },
];
